config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root :to => 'static_pages#home'
  devise_for :users
  resources :users do
    resources :images
  end
end


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user

  has_attached_file :photo, :styles => {:medium => "300x300>"}, :default_url => "http://library.sandiegozoo.org/factsheets/capybara/images/capybara.jpg"

  validates :title, :presence => true
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :images
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable

has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "https://pbs.twimg.com/profile_images/601627261280722944/fSw32Fgs.jpg"
validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @images = Image.all
    @users = User.all
    # @user = User.find(params[:id])
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = current_user.images.new
  end


  def create
    @image = current_user.images.new(image_params)
    if @image.save
      redirect_to root_path
    else
      binding.pry
      render :new
    end
  end

  def edit
      @image = Image.find(params[:id])
    end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      flash[:notice] = "Image successfully updated"
      redirect_to images_path
    else
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to user_images_path
  end


private
  def image_params
    params.require(:image).permit(:photo, :tag, :title)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :authenticate_user!
  
  def home

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.erb
<%= render 'layouts/errors', :object => @image %>

<%= form_for [current_user, @image], url: user_images_path, html: { multipart: true } do |f| %>
  <%= f.label :photo, :class => 'col-sm-2 control-label'%>
  <%= f.file_field :photo, :class => "form-control" %>

  <%= f.label :title, :class => 'col-sm-2 control-label'  %>
  <%= f.text_field :title, :class => 'form-control'  %>

  <%= f.label :tag, :class => 'col-sm-2 control-label'  %>
  <%= f.text_field :tag, :class => 'form-control'  %>

  <%= f.submit :class => "btn btn-success" %>
<% end %>

app/views/images/edit.html.erb
<h1>Edit image</h1>

<%= render 'form' %>

app/views/images/index.html.erb
<button class="btn btn-success"><%= link_to 'Add New Photo', new_user_image_path %></button>
<br>
<br>
<% @images.each do |image| %>
  Title: <%= image.title %> <br>
  Posted by: <%= image.user.email %>
  <%= image_tag image.photo.url(:medium) %><br>
  Tag: <%= image.tag %>
  <br>
  <br>
<% end %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

app/views/images/show.html.erb
<h1>Images</h1>
<%= image_tag @image.photo.url(:medium) %>

<% if current_user.id == @image.user_id %>
  <%= link_to "Edit Image", edit_user_image_path(current_user, @image) %>
  <%= link_to "Delete", user_image_path(current_user, @image), :data => {:confirm => "You sure?",                             :method => "delete"} %>
<% end %>

app/views/layouts/_errors.html.erb
<% if @image.errors.any? %>
  <h4>There seems to be an error... </h4>
    <ul>
      <% @image.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
            <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>

            <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>

            <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
        </ul>
    </div>
    <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>HELLO!</h1>
<li><%= link_to 'Images', user_images_path(current_user) %></li>